### ISSUE TITLE
e2e script fails to recognize the event and proceed to next step to executeCall when we make EVM <-> EVM transaction

### ISSUE THREAD

**Issue by hemz10** [icon-project/btp2#37] opened 2023-06-13 12:16 UTC
**Describe the issue**
When I make a transaction from evm to evm using e2e demo script, script stops at checking callMessage event on destination chain even though the event is received on destination chain. If e2e demo script can identify the events from evm to evm transaction too then it will be easy to test using the script itself. Currently to execute call I had to manually check for the event and get reqId from the block explorer and execute call.

Note : JVM to EVM and vice versa works well without any issues.

**To reproduce**
1. Make an simple evm to evm transaction using e2e demo script 
2. After message is sent from source, observe
3. Script will wait for sometime, will not identify the event and it will fail with timout error without executing call on destination chain

**Expected behavior**
Script should complete transaction. 

**System information (please complete the following information):**
 - OS linux

**Additional context**
Here are some transactions for reference. 
This is sendCallMessage from BSC - https://testnet.bscscan.com/tx/0x9f0106d2e829cede19ba1091e2ae1464bcacdaf59621a40e96b0e4a37376116a
Through Icon Berlin - https://berlin.tracker.solidwallet.io/transaction/0xc1c70f344451fd25ea3ab92be9a79af4393ca5e91619974dca0fca8077da674f
And Call Message Event received in Sepolia - https://sepolia.etherscan.io/tx/0xd3df3c0a49284dfedb95f6ce82a58403253cec93ec2bb13c2cb8da4e7bf8a9b6

Even though callMessage event is received in Sepolia, e2e script fails to recognize the event and proceed to next step to executeCall
https://github.com/icon-project/btp2/blob/main/e2edemo/scripts/demo_dapp.ts#L159

This happens for Sepolia to BSC too.

**Comment by mksong-icon** [comment] 2023-06-23 02:24
We found some problems in receiving events in EVM. You may try a new version.

Regardless of this, it's just for demonstration, so it may not be maintained fully functional. Of course, these kinds of issues may be ignored.

**Comment by sink772** [comment] 2023-06-23 07:15
As I described in [README](https://github.com/icon-project/btp2/blob/main/e2edemo/README.md) file in e2edemo, the purpose of the script is just for demonstration.  It was not designed for complex real world test scenarios.

From what I understand, the purpose of the focus testing is to validate the BTP2 network itself and protocols, not to debug the e2edemo script.  If needed for your testing, you should even develop your own test script.  So if you have confirmed the message delivery between BSC <-> ICON <-> Sepolia successfully, then the basic purpose of the focus testing is done.

Nevertheless, I do not see any reason why the e2edemo script fails to recognize the CallMessage event as you reported, since the EVM handling part is working well for both SRC and DST chains.  I'm not sure, but it may be related to timeout issue.

**Comment by mksong76** [comment] 2023-07-11 02:05
No respose, so close it.

**Closed by mksong76** 2023-07-11 02:05 UTC
